import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link, NavLink } from "react-router-dom";
import { cx } from "@ai-music/ui";
import { appMeta } from "@ai-music/config";
import { navItems, secondaryItems } from "../data/options";
export function Layout(props) {
    return (_jsxs("div", { className: "app-shell", children: [_jsx("div", { className: "ambient ambient-left" }), _jsx("div", { className: "ambient ambient-right" }), _jsxs("header", { className: "topbar", children: [_jsxs(Link, { className: "brand", to: "/", children: [_jsx("span", { className: "brand-mark", "aria-hidden": "true", children: _jsxs("svg", { viewBox: "0 0 24 24", width: "20", height: "20", fill: "none", stroke: "currentColor", strokeWidth: "2.4", strokeLinecap: "round", strokeLinejoin: "round", children: [_jsx("path", { d: "M9 18V5l12-2v13" }), _jsx("circle", { cx: "6", cy: "18", r: "3" }), _jsx("circle", { cx: "18", cy: "16", r: "3" })] }) }), _jsxs("div", { children: [_jsx("strong", { children: appMeta.name }), _jsx("p", { children: appMeta.tagline })] })] }), _jsx("nav", { className: "nav", "aria-label": "\u4E3B\u5BFC\u822A", children: navItems.map((item) => (_jsx(NavLink, { to: item.path, className: ({ isActive }) => cx("nav-link", isActive && "nav-link-active"), end: item.path === "/", children: item.label }, item.path))) }), _jsxs("button", { className: "ghost-button", onClick: () => void props.onRefresh(), type: "button", "aria-label": "\u5237\u65B0\u6570\u636E", children: [_jsxs("svg", { viewBox: "0 0 24 24", width: "14", height: "14", fill: "none", stroke: "currentColor", strokeWidth: "2.4", strokeLinecap: "round", strokeLinejoin: "round", style: { marginRight: "0.4rem", verticalAlign: "-2px" }, children: [_jsx("path", { d: "M21 12a9 9 0 1 1-3-6.7" }), _jsx("path", { d: "M21 4v5h-5" })] }), "\u5237\u65B0\u6570\u636E"] })] }), _jsxs("main", { className: "page", children: [props.error ? _jsx(ErrorBanner, { message: props.error }) : null, props.children] }), _jsx("footer", { className: "layout-footer", children: secondaryItems.map((item) => (_jsx(Link, { to: item.path, className: "footer-link", children: item.label }, item.path))) })] }));
}
function ErrorBanner(props) {
    return (_jsxs("div", { className: "error-banner", role: "alert", children: [_jsxs("strong", { style: { display: "inline-flex", alignItems: "center", gap: "0.4rem", marginRight: "0.5rem" }, children: [_jsxs("svg", { viewBox: "0 0 24 24", width: "14", height: "14", fill: "none", stroke: "currentColor", strokeWidth: "2.4", strokeLinecap: "round", strokeLinejoin: "round", children: [_jsx("circle", { cx: "12", cy: "12", r: "10" }), _jsx("line", { x1: "12", y1: "8", x2: "12", y2: "12" }), _jsx("line", { x1: "12", y1: "16", x2: "12.01", y2: "16" })] }), "\u63A5\u53E3\u9519\u8BEF"] }), props.message] }));
}
